apiVersion: v1
kind: Pod
metadata:
  name: ubi8-build-test
spec:
  containers:
    - name: ubi8-build-test
      image: registry.access.redhat.com/ubi8:latest 
      command: [ "/bin/sh", "-c", "dnf search kernel-devel --showduplicates" ]
  restartPolicy: Never